mon_etab/api/urls.py
from django.urls import path, include
from rest_framework import routers
from .api_views.student_api_view import student_list,student_detail
from .api_views.teacher_api_view import teacher_list
from .api_views.user_api_view import user_list
from .api_views.absence_api_view import absence_list
from .api_views.app_setting_api_view import app_setting_list
from .api_views.role_user_api_view import role_user_list
from .api_views.school_api_view import school_list
from .api_views.student_card_api_view import student_card_list

router = routers.DefaultRouter()
#router.register(prefix

urlpatterns = [

    path('students/',student_list),
    path('students/<int:pk>/',student_detail),




    path('teachers/',teacher_list),
    path('users/',user_list),
    path('absence/',absence_list),
    path('app_settings/',app_setting_list),
    path('role_users/',role_user_list),
    path('schools/',school_list),
    path('student_cards/',student_card_list),

]

mon_etab/mon_etab/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/', include('base.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('user/', include('user.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('rapport/', include('rapport.urls')),
    path('', include('school.urls')),
    path('login/', include('login.urls')),


    path('api/', include('api.urls')),


]

mon_etab/user/urls.py
from django.urls import path

from user.views import adresse_view
from .views import *

app_name = 'user'

urlpatterns = [
     
    # User CRUD Operations
    path('', user_view.list_user, name='list_user'),
    path('add_user', user_view.add_user, name='add_user'),
    path('update_user/<int:id>', user_view.update_user, name='update_user'),
    path('delete_user/<int:id>', user_view.delete_user, name='delete_user'),

    # Adresse CRUD Operations
    path('list_adresse', adresse_view.list_adresse, name='list_adresse'),
    path('add_adresse', adresse_view.add_adresse, name='add_adresse'),
    path('update_adresse/<int:id>', adresse_view.update_adresse, name='update_adresse'),
    path('delete_adresse/<int:id>', adresse_view.delete_adresse, name='delete_adresse'),

    # RoleUser CRUD Operations
    path('list_roleUser', roleUser_view.list_roleUser, name='list_roleUser'),
    path('add_roleUser', roleUser_view.add_roleUser, name='add_roleUser'),
    path('update_roleUser/<int:id>', roleUser_view.update_roleUser, name='update_roleUser'),
    path('delete_roleUser/<int:id>', roleUser_view.delete_roleUser, name='delete_roleUser'),

    path('deactivate_user/<int:id>', user_view.deactivate_user, name='deactivate_user'),







]

mon_etab/user/models/roleUser_model.py
from django.db import models
from base.models.helpers.date_time_model import DateTimeModel

class RoleUser(DateTimeModel):
    role = models.CharField(max_length=255) 

    def __str__(self) -> str:
        return self.role

    

mon_etab/user/models/user_model.py
from django.db import models

from base.models.helpers.date_time_model import DateTimeModel
from school.models.school_model import School
from .roleUser_model import RoleUser
from django.contrib.auth.models import AbstractUser

class UserApps(AbstractUser):
    role = models.ManyToManyField(RoleUser)
    school = models.ForeignKey(School, on_delete=models.CASCADE, null=True, blank=True)


    # relation One to One with Person Class

    # person_id = models.OneToOneField(Person, on_delete=models.CASCADE, related_name='user_person_ids')

    def __str__(self) -> str:
        return f"{self.username} : {self.date_joined}"


 

mon_etab/user/forms/adresse_form.py
from django import forms 

from base.models.helpers.adresse_model import Adresse

class AdresseForms(forms.ModelForm):
    class Meta:
        model = Adresse
        fields = "__all__"

mon_etab/user/forms/roleUser_form.py
from django import forms 

from ..models.roleUser_model import RoleUser

class RoleUserForms(forms.ModelForm):
    class Meta:
        model = RoleUser
        fields = "__all__"

mon_etab/user/forms/user_form.py
from django import forms 

from ..models.user_model import UserApps

class UserAppForms(forms.ModelForm):
    class Meta:
        model = UserApps
        fields = ("username","password","is_active")

mon_etab/user/views/adresse_view.py
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist

from base.models.helpers.adresse_model import Adresse
from ..forms.adresse_form import AdresseForms
from django.contrib.auth.decorators import login_required
from school.models.school_model import School
from school.models.appSetting_model import AppSetting

# Create your views here.

@login_required()
def list_adresse(request):
    app_setting_total = AppSetting.objects.all()
    school_total = School.objects.all()
    adresses = Adresse.objects.all()
    context = {
        'adresses': adresses,
        'app_setting_total': app_setting_total,
        'school_total': school_total,
    }
    return render(request, 'adresse/list_adresse.html', context)


@login_required()
def add_adresse(request):
    app_setting_total = AppSetting.objects.all()
    school_total = School.objects.all
    adresse_form = AdresseForms()

    if request.method == 'POST':
        adresse_form = AdresseForms(request.POST)
        if adresse_form.is_valid():
            adresse_form.save()
            return redirect('user:list_adresse')

    context = {
        'title': 'Ajouter une Adresse',
        'adresse_form': adresse_form,
        'app_setting_total': app_setting_total,
        'school_total': school_total,
    }
    return render(request, 'adresse/add_adresse.html',context)

@login_required()
def update_adresse(request, id):
    app_setting_total = AppSetting.objects.all()
    school_total = School.objects.all()

    context = {
        "title": 'Modifier Adresse',
        'app_setting_total': app_setting_total,
        'school_total': school_total,
    }
    try:
        adresse = Adresse.objects.get(id=id)
    except ObjectDoesNotExist:
        print(f"Adresse does not exist !!")
        return redirect('user:list_adresse')

    if request.method == 'POST':
        adresse_form = AdresseForms(data=request.POST, instance=adresse)
        if adresse_form.is_valid():
            adresse_form.save()
            return redirect('user:list_adresse')
    adresse_form = AdresseForms(instance=adresse)
    context["adresse_form"] = adresse_form

    return render(request, 'adresse/add_adresse.html', context)


@login_required()
def delete_adresse(request,id):
    try:
        adresse = Adresse.objects.get(id=id)
    except ObjectDoesNotExist:
        print(f"Adresse does not exist !!")
        return redirect('user:list_adresse')

    adresse.delete()
    return redirect('user:list_adresse')

mon_etab/user/views/roleUser_view.py
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist

from ..models.roleUser_model import RoleUser
from ..forms.roleUser_form import RoleUserForms
from django.contrib.auth.decorators import login_required
from school.models.school_model import School
from school.models.appSetting_model import AppSetting

# Create your views here.


@login_required()
def list_roleUser(request):
    app_setting_total = AppSetting.objects.all()
    school_total = School.objects.all()
    roleUsers = RoleUser.objects.all()
    context = {
        'roleUsers': roleUsers,
        'app_setting_total': app_setting_total,
        'school_total': school_total,
    }
    return render(request, 'roleUser/list_roleUser.html', context)


@login_required()
def add_roleUser(request):
    app_setting_total = AppSetting.objects.all()
    school_total = School.objects.all()
    roleUsers_form = RoleUserForms()

    if request.method == 'POST':
        roleUsers_form = RoleUserForms(request.POST)
        if roleUsers_form.is_valid():
            roleUsers_form.save()
            return redirect('user:list_roleUser')

    context = {
        'title': 'Ajouter un Role Utilisateur',
        'roleUsers_form': roleUsers_form,
        'app_setting_total': app_setting_total,
        'school_total': school_total,
    }
    return render(request, 'roleUser/add_roleUser.html',context)


@login_required()
def update_roleUser(request, id):
    app_setting_total = AppSetting.objects.all()
    school_total = School.objects.all()
    context = {
        "title": 'Modifier Role Utilisateur',
        'app_setting_total': app_setting_total,
        'school_total': school_total,
    }
    try:
        roleUser = RoleUser.objects.get(id=id)
    except ObjectDoesNotExist:
        print(f"RoleUser does not exist !!")
        return redirect('user:list_roleUser')

    if request.method == 'POST':
        roleUsers_form = RoleUserForms(data=request.POST, instance=roleUser)
        if roleUsers_form.is_valid():
            roleUsers_form.save()
            return redirect('user:list_roleUser')
    roleUsers_form = RoleUserForms(instance=roleUser)
    context["roleUsers_form"] = roleUsers_form

    return render(request, 'roleUser/add_roleUser.html', context)


@login_required()
def delete_roleUser(request,id):
    try:
        roleUser = RoleUser.objects.get(id=id)
    except ObjectDoesNotExist:
        print(f"RoleUser does not exist !!")
        return redirect('user:list_roleUser')

    roleUser.delete()
    return redirect('user:list_roleUser')

mon_etab/user/views/user_view.py
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required

from teacher.models.teacher_model import Teacher

from ..models.user_model import UserApps
from ..forms.user_form import UserAppForms
from django.contrib.auth.decorators import login_required
from school.models.school_model import School
from school.models.appSetting_model import AppSetting

# Create your views here.


@login_required()
def list_user(request):
    search_area = request.GET.get('name')
    app_setting_total = AppSetting.objects.all()
    school_total = School.objects.all()

    if search_area:
        search_user = UserApps.objects.filter(username__icontains = search_area )
        # print(f"user status :  {search_user.values_list}")
        count_user = search_user.count()
        context = {
            'users':search_user,
            'count_user': count_user,
            'app_setting_total': app_setting_total,
            'school_total': school_total,
        }
    else :
        users = UserApps.objects.all()

        count_user = users.count()
        context = {
            'users': users,
            'count_user': count_user,
            'app_setting_total': app_setting_total,
            'school_total': school_total,
        }
    return render(request, 'user/list_user.html', context)


@login_required()
def add_user(request):
    app_setting_total = AppSetting.objects.all()
    school_total = School.objects.all()
    user_form = UserAppForms()

    if request.method == 'POST':

        print(f"request.POST.get('password') : {request.POST.get('password')}")
        user_form = UserAppForms(request.POST)
        if user_form.is_valid():
            print(f'user password : {user_form.save().password}' )
            user_form.save(commit=False).set_password(user_form.save().password)
            user_form.save()
            # user_form.save().set_password(user_form.save().password)

            return redirect('user:list_user')

    context = {
        'title': 'Ajouter un Utilisateur',
        'user_form': user_form,
        'app_setting_total': app_setting_total,
        'school_total': school_total,
    }
    return render(request, 'user/add_user.html',context)


@login_required()
def update_user(request, id):
    app_setting_total = AppSetting.objects.all()
    school_total = School.objects.all()

    context = {
        "title": 'Modifier Utilisateur',
        'app_setting_total': app_setting_total,
        'school_total': school_total,
    }
    try:
        user = UserApps.objects.get(id=id)
    except ObjectDoesNotExist:
        print(f"User does not exist !!")
        return redirect('user:list_user')

    if request.method == 'POST':
        user_form = UserAppForms(data=request.POST, instance=user)
        if user_form.is_valid():
            user_form.save()
            return redirect('user:list_user')
    user_form = UserAppForms(instance=user)
    context["user_form"] = user_form

    return render(request, 'user/add_user.html', context)


@login_required()
def delete_user(request, id):
    try:
        user = UserApps.objects.get(id=id)
    except ObjectDoesNotExist:
        print(f"user does not exist !!")
        return redirect('user:list_user')

    user.delete()
    return redirect('user:list_user')



def login(request):
    username = request.POST.get('username')
    password = request.POST.get('password')

    # if not username in request.Post

    if not username and not password:
        return redirect('user:login')

    check_username = UserApps.objects.filter(username__exact = username, password__exact = password)
    if not check_username:
        print("Wrong connexion !!!!")
        return redirect('user:login')
    return redirect('school:check_app_setting')


@login_required()
def deactivate_user(request,id):
    try:
        user = UserApps.objects.get(id=id)
        print(f"status user : {user.is_active}")

    except ObjectDoesNotExist:
        return redirect('user:list_user')

    user.is_active = False
    print(f"status user after search : {user.is_active}")

    user.save()
    context = {
        'users' : UserApps.objects.all(),
        'count_user': UserApps.objects.all().count(),
    }

    return render(request, 'user/list_user.html', context)

mon_etab/templates/user/add_user.html
{% extends "sidebar.html" %}
{% load static %}

{% block content %}
    <section class="flex flex-col items-center justify-center mt-10">
        <h2 class="text-3xl font-bold text-gray-800 mb-8">
            <i class="fas fa-pencil-alt"></i> {{ title }}
        </h2>

        <form action="" method="post" class="w-full max-w-lg bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="mb-6 space-y-4">
                {{ user_form.as_p }}
            </div>

            <div class="flex justify-between mt-6">
                <a href="{% url 'user:list_user' %}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                    Annuler
                </a>
                <button type="submit" name="enregistrer" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                    Enregistrer
                </button>
            </div>
        </form>
    </section>
{% endblock content %}

mon_etab/templates/user/list_user.html
{% extends "sidebar.html" %}

{% block content %}
<div class="container mx-auto px-4 py-8">
    <div class="bg-white shadow-md rounded-lg p-6">
        <!-- En-tête avec titre et actions -->
        <div class="flex justify-between items-center mb-6">
            <h2 class="text-2xl font-semibold text-gray-700">
                Informations sur les Utilisateurs ({{ count_user }})
            </h2>
            <div class="flex space-x-4">
                <!-- Bouton d'ajout d'utilisateur -->
                <a href="{% url 'user:add_user' %}" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 flex items-center">
                    <i class="fas fa-plus-circle mr-2"></i> Ajouter un Utilisateur
                </a>
                <!-- Barre de recherche -->
                <form method="get" class="flex items-center">
                    <input
                        type="text"
                        name="name"
                        value="{{ search_area }}"
                        class="border border-gray-300 px-3 py-2 rounded-l-lg focus:outline-none focus:ring-2 focus:ring-blue-400"
                        placeholder="Rechercher un utilisateur"
                    />
                    <button type="submit" class="bg-green-500 text-white px-4 py-2 rounded-r-lg hover:bg-green-600">
                        Recherche
                    </button>
                </form>
            </div>
        </div>

        <!-- Tableau des utilisateurs -->
        <div class="overflow-x-auto">
            <table class="min-w-full bg-white table-auto border-collapse">
                <thead>
                    <tr class="bg-gray-800 text-white text-left">
                        <th class="px-4 py-2">Pseudo</th>
                        <th class="px-4 py-2">Date de création</th>
                        <th class="px-4 py-2">Statut</th>
                        <th class="px-4 py-2 text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% if users %}
                        {% for user in users %}
                        <tr class="border-b">
                            <td class="px-4 py-2">{{ user.username }}</td>
                            <td class="px-4 py-2">{{ user.date_joined|date:"Y-m-d" }}</td>
                            <td class="px-4 py-2">{{ user.is_active }}</td>
                            <td class="px-4 py-2 text-center space-x-2">
                                <!-- Bouton Modifier -->
                                <a href="{% url 'user:update_user' user.id %}" class="bg-yellow-500 text-white px-4 py-2 rounded hover:bg-yellow-600">
                                    Modifier
                                </a>
                                <!-- Bouton Supprimer -->
                                <button onclick="notif({{ user.id }})" class="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600">
                                    Supprimer
                                </button>
                                <!-- Bouton Désactiver -->
                                <button onclick="notifDesactiver({{ user.id }})" style="background-color: green; color: white; padding: 10px 20px; border-radius: 5px; border: none; cursor: pointer;">
                                    Désactiver
                                </button>

                            </td>
                        </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="4" class="text-center text-red-500 py-4">
                                <h3>Aucune information disponible pour le moment.</h3>
                            </td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

{% block notif_javascript %}
<script>
    function notif(user) {
        const deleteUrl = "{% url 'user:delete_user' 0 %}".replace('0', user);
        Swal.fire({
            title: "Êtes-vous sûr de vouloir supprimer ?",
            icon: "warning",
            showCancelButton: true,
            confirmButtonText: "Oui, supprimer",
            cancelButtonText: "Non",
            dangerMode: true,
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = deleteUrl;
            }
        });
    }

    function notifDesactiver(user) {
        const deactivateUrl = "{% url 'user:deactivate_user' 0 %}".replace('0', user);
        Swal.fire({
            title: "Êtes-vous sûr de vouloir désactiver ?",
            icon: "warning",
            showCancelButton: true,
            confirmButtonText: "Oui, désactiver",
            cancelButtonText: "Non",
            dangerMode: true,
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = deactivateUrl;
            }
        });
    }
</script>
{% endblock notif_javascript %}